//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a10
    {
        public int OBJECTID_1 { get; set; }
        public string F97m { get; set; }
        public string F97t { get; set; }
        public string F97e { get; set; }
        public string Code_Block { get; set; }
        public string Code_Band { get; set; }
        public string Name { get; set; }
        public string W { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
