//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a11
    {
        public int OBJECTID { get; set; }
        public string malek { get; set; }
        public Nullable<decimal> id { get; set; }
        public string name { get; set; }
        public Nullable<int> ORIG_FID { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
