//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a14
    {
        public int OBJECTID { get; set; }
        public string Parvaneh { get; set; }
        public string Code_Block { get; set; }
        public Nullable<decimal> Amlak__ { get; set; }
        public string COD { get; set; }
        public string Code_nosazi { get; set; }
        public Nullable<decimal> Mantaghe { get; set; }
        public Nullable<decimal> Mahale { get; set; }
        public Nullable<decimal> Block { get; set; }
        public Nullable<decimal> Melk { get; set; }
        public string Name_malek { get; set; }
        public string Address { get; set; }
        public string Malekiyat { get; set; }
        public string Mahiyate_fiziki { get; set; }
        public string Karbari { get; set; }
        public string Sanad { get; set; }
        public string Marhale_sakhtemani { get; set; }
        public string Masahat { get; set; }
        public string pelakabi { get; set; }
        public string codeposti { get; set; }
        public string Archive_No { get; set; }
        public string mogheyat { get; set; }
        public string bakhsh { get; set; }
        public string asli { get; set; }
        public string fari { get; set; }
        public string tafkiki { get; set; }
        public string Telephone { get; set; }
        public string COD_1 { get; set; }
        public Nullable<int> Parvande_No { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
