//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GH1396_E
    {
        public int OBJECTID { get; set; }
        public string F91 { get; set; }
        public string F87 { get; set; }
        public string F85 { get; set; }
        public string F84 { get; set; }
        public string F83 { get; set; }
        public string F82 { get; set; }
        public string F81 { get; set; }
        public string F71 { get; set; }
        public string F68 { get; set; }
        public string F64 { get; set; }
        public string F95 { get; set; }
        public string F96 { get; set; }
        public string F65 { get; set; }
        public string F66 { get; set; }
        public string F67 { get; set; }
        public string F69 { get; set; }
        public string F70 { get; set; }
        public string F72 { get; set; }
        public string F73 { get; set; }
        public string F74 { get; set; }
        public string F75 { get; set; }
        public string F76 { get; set; }
        public string F77 { get; set; }
        public string F78 { get; set; }
        public string F79 { get; set; }
        public string F80 { get; set; }
        public string F86 { get; set; }
        public string F88 { get; set; }
        public string F89 { get; set; }
        public string F90 { get; set; }
        public string F92 { get; set; }
        public string F93 { get; set; }
        public string F94 { get; set; }
        public string Code_Block { get; set; }
        public string Code_Band { get; set; }
        public string Name { get; set; }
        public string W { get; set; }
    }
}
