//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NAME
    {
        public int OBJECTID { get; set; }
        public string Name { get; set; }
        public string W { get; set; }
        public string Code_M { get; set; }
    }
}
