//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAABER_PT
    {
        public int OBJECTID_1 { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<decimal> Shape_Leng { get; set; }
    }
}
