//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_compress_log
    {
        public int compress_id { get; set; }
        public int sde_id { get; set; }
        public int server_id { get; set; }
        public string direct_connect { get; set; }
        public System.DateTime compress_start { get; set; }
        public int start_state_count { get; set; }
        public Nullable<System.DateTime> compress_end { get; set; }
        public Nullable<int> end_state_count { get; set; }
        public string compress_status { get; set; }
    }
}
