//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicesSetting
    {
        public int ID { get; set; }
        public string mapService { get; set; }
        public string printService { get; set; }
        public string geometryService { get; set; }
    }
}
