//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_GEOMETRY_COLUMNS
    {
        public string table_schema { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string type_schema { get; set; }
        public string type_name { get; set; }
        public int srs_id { get; set; }
    }
}
