//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_SPATIAL_REFERENCE_SYSTEMS
    {
        public int srs_id { get; set; }
        public double x_offset { get; set; }
        public double x_scale { get; set; }
        public double y_offset { get; set; }
        public double y_scale { get; set; }
        public double z_offset { get; set; }
        public double z_scale { get; set; }
        public double m_offset { get; set; }
        public double m_scale { get; set; }
        public string organization { get; set; }
        public Nullable<int> organization_coordsys_id { get; set; }
        public string definition { get; set; }
    }
}
